### ISSUE TITLE
Logs forwarder does not work with runtime python3.8

### ISSUE THREAD

**Issue by duy-nguyen-xb** [DataDog/datadog-serverless-functions#506]
**Describe what happened:**
I install a datadog-forwarder lambda by using a release artifact downloaded from [your releases](https://github.com/DataDog/datadog-serverless-functions/releases).

The lambda uses runtime **python3.8** and throws the below error when it is triggered
`Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)`

The lambda with **release 3.29.0 still works as expected on python3.8**, but **starts to fail from version 3.30.0**, same error for the latest version 3.39.0.

As for checking, I see a [dependency upgrade](https://github.com/DataDog/datadog-serverless-functions/pull/436) in that version. Is it a change that required additional adjustment to allow the lambda can run with python3.8?

**Describe what you expected:**
Log forwarder lambda with the latest version (3.39.0) can work with the runtime python3.8

**Steps to reproduce the issue:**
* Create a Python 3.8 Lambda function using [aws-dd-forwarder-3.39.0.zip](https://github.com/DataDog/datadog-serverless-functions/releases).
* Save Datadog API key in AWS Secrets Manager, set environment variable DD_API_KEY_SECRET_ARN with the secret ARN on the Lambda function.
* Add required permissions to lambda
* [Configure trigger from S3](https://docs.datadoghq.com/integrations/amazon_s3/)

**Comment by tianchu** [comment]
@duy-nguyen-xb Thanks for your detailed report! Although I'm not yet sure why it doesn't work in Python3.8, the forwarder is indeed supposed to be running on 3.7 for now (we do need to upgrade and test against 3.8 or 3.9 at some point). Can you try using Python3.7, just to see if that helps unblock you?

**Comment by duy-nguyen-xb** [comment]
@tianchu Thanks for your information!

We have several lambda functions in the system, and we maintain a consistent runtime environment for them.
For now, downgrading the forwarder to version 3.29.0 works fine with Python3.8. We can stay with it for a while longer.
And in case that you release a critical version, e.g. for a security patch, we may consider downgrading the runtime to Python3.7.

However, as I see your integration tests are supporting building with Python3.8, we still looking forward to your awesome functions that can run on newer Python versions. That will be superb!

**Comment by tianchu** [comment]
@duy-nguyen-xb  The reason it doesn't work in your case is that the release bundle (zip) is built under Python3.7 https://github.com/DataDog/datadog-serverless-functions/blob/2c2712b950a0b690c2d40cd2a3c058bb4c9c82f1/aws/logs_monitoring/tools/build_bundle.sh#L25, and a upstream dependency includes C extensions that only work against the Python version where it was built. Therefore, that zip only works under Python3.7. I'm not actually sure we will ever upgrade to Python3.8, because more likely we would skip it and upgrade to the latest Python runtime version.

We don't normally recommend customers building their own version of the Forwarder, but it might be fine if you are installing the forwarder using manual steps anyway. You can try alter the [line](https://github.com/DataDog/datadog-serverless-functions/blob/2c2712b950a0b690c2d40cd2a3c058bb4c9c82f1/aws/logs_monitoring/tools/build_bundle.sh#L25) I mentioned earlier to Python3.8 and run the script build_bundle.sh mentioned [here](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#contributing) to get a forwarder zip that is compatible with Python3.8.

**Comment by duy-nguyen-xb** [comment]
@tianchu

Thanks for the quick investigation and suggestion!

I think this issue can be closed according to your plan:
> I'm not actually sure we will ever upgrade to Python3.8, because more likely we would skip it and upgrade to the latest Python runtime version.

I am looking forward to the next coming release on the latest Python version.
